stack/website/secondtour_website/website/routes/professeur_routes.py
import logging
from flask import Blueprint, render_template, session, request, redirect, url_for
from flask.helpers import flash
import os

from ..function import main_security, main_sessions, main_database, main_calendrier
from ..database.main_database import *

professeur_routes = Blueprint('professeur_routes', __name__,
                              template_folder='templates',
                              static_folder='static')


@professeur_routes.route('/')
@professeur_routes.route('/accueil')
def accueil():
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-professeur",
            "data": {
                "target": "website:website-professeur"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-professeur:website-professeur-accueil",
            "data": {
                "target": "website-professeur:website-professeur-accueil"
            }
        })
    
    
    if main_security.test_session_connected(session, False):
        id_matieres = []
        all_professeurs = []
        response_prof = ask_api(
            "data/fetch/professeur", {})
        professeurs = response_prof.json()
        for professeur in professeurs:
            all_professeurs.append(professeur)
        id_salle = []
        response_utilisateurs = ask_api(
            "data/fetch/utilisateur", {})
        for utilisateur in response_utilisateurs.json():
            if utilisateur['email'] == session['email']:
                response_prof = ask_api(
                    "data/fetch/professeur", {})
                for professeur in response_prof.json():
                    if professeur['id_professeur'] == utilisateur['id_professeur']:
                        response_liste = ask_api(
                            "data/fetch/liste_matiere", {})
                        for liste_matiere in response_liste.json():
                            if liste_matiere['id_professeur'] == professeur['id_professeur']:
                                id_matieres.append(liste_matiere['id_matiere'])
                        id_salle.append(professeur['salle'])
        response_salle = ask_api(
            "data/fetch/salle", {})
        salles = response_salle.json()
        all_salles = []
        for salle in salles:
            all_salles.append(salle)
        response_candidat = ask_api(
            "data/fetch/candidat", {})
        all_candidats = response_candidat.json()
        response_creneau = ask_api(
            "data/fetch/creneau", {})
        all_creneaux = response_creneau.json()
        for creneau in all_creneaux:
            creneau["debut_preparation"] = datetime.strptime(creneau["debut_preparation"], '%a %b %d %H:%M:%S %Y') if type(
                creneau["debut_preparation"]) == str else creneau["debut_preparation"]
            creneau["fin_preparation"] = datetime.strptime(creneau["fin_preparation"], '%a %b %d %H:%M:%S %Y') if type(
                creneau["fin_preparation"]) == str else creneau["fin_preparation"]
            creneau["fin"] = datetime.strptime(creneau["fin"], '%a %b %d %H:%M:%S %Y') if type(
                creneau["fin"]) == str else creneau["fin"]
        return render_template('professeur/accueil.html', id_matieres=id_matieres, all_candidats=all_candidats, all_creneaux=all_creneaux, id_salle=id_salle, all_professeurs=all_professeurs, all_salles=all_salles)
    else:
        return redirect(url_for('main_routes.connexion'))


@professeur_routes.route('/deconnexion')
def deconnexion():
    if session['email']:
        session.pop('email', None)
    if session['password']:
        session.pop('password', None)
    flash('Vous avez correment été déconnecté', 'primary')
    logging.warning('Vous avez correctement été déconnecté')
    return redirect(url_for('main_routes.index'))


if(os.getenv("NETWORK_VISU") == "true"):
    
    
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-professeur",
        "data": {
                "name": "Professeur",
                "id": "website-professeur",
                "size": 46,
                "fsize": 30
        },
        "position": {
            "x": 711,
            "y": 615
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website:website-professeur",
        "data": {
                "id": "website:website-professeur",
                "weight": 1,
                "source": "website",
                "target": "website-professeur"
        }
    })
    
    
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-professeur-accueil",
        "data": {
                "name": "Accueil",
                "id": "website-professeur-accueil",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 825,
            "y": 670
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-professeur:website-professeur-accueil",
        "data": {
                "id": "website-professeur:website-professeur-accueil",
                "weight": 1,
                "source": "website-professeur",
                "target": "website-professeur-accueil"
        }
    })
    
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-professeur-compte",
        "data": {
                "name": "Création de compte",
                "id": "website-professeur-compte",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 825,
            "y": 611
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-professeur:website-professeur-compte",
        "data": {
                "id": "website-professeur:website-professeur-compte",
                "weight": 1,
                "source": "website-professeur",
                "target": "website-professeur-compte"
        }
    })

stack/website/secondtour_website/website/templates/professeur/accueil.html
{% extends "professeur/base_professeur.html" %} {% block title
%}Administration{% endblock %} {% block sub_content %}
<div class="main-div-admin">
  <div class="main-table-admin">
    {%- for category, message in get_flashed_messages(with_categories = true) %}
    <div
      class="alert alert-{{category}}  alert-dismissible fade show"
      role="alert"
    >
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%- endfor %}
    <div class="table-responsive thumbnail">
      <table
        class="table table-light table-striped table-hover"
        id="tableAccordion1"
      >
        <thead>
          <tr>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Heure de début préparation</th>
            <th scope="col">Fin prépa</th>
            <th scope="col">Heure de fin</th>
            <th scope="col" class="hide">Emargement</th>
          </tr>
        </thead>
        <tbody>
          {% for creneau in all_creneaux %} {% if creneau.id_matiere in
          id_matieres and creneau.id_salle in id_salle %}
          <tr>
            {% for candidat in all_candidats %} {% if candidat.id_candidat ==
            creneau.id_candidat %}
            <td scope="row">{{candidat.nom}}</td>
            <td scope="row">{{candidat.prenom}}</td>
            {% endif %} {% endfor %}
            <td scope="row">
              Jour {{creneau.debut_preparation.strftime("%d")}} |
              {{creneau.debut_preparation.strftime("%H:%M")}}
            </td>
            <td scope="row">
              Jour {{creneau.fin_preparation.strftime("%d")}} |
              {{creneau.fin_preparation.strftime("%H:%M")}}
            </td>
            <td scope="row">
              Jour {{creneau.fin.strftime("%d")}} | {{creneau.fin.strftime("%H:%M")}}
            </td>
            <td scope="row" class="hide"></td>
          </tr>
          {% endif %} {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

stack/website/secondtour_website/website/templates/professeur/base_professeur.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='admin.css')}}">
{% endblock %}
{% block content %}
<div class="d-flex flex-column vh-100 flex-shrink-0 p-3 text-white bg-dark" style="width: 250px; z-index: 1;">
  <a href="{{url_for('professeur_routes.accueil')}}"
    class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <svg class="bi me-2" width="40" height="32"></svg>
    <span class="fs-4">Espace professeur</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="{{url_for('professeur_routes.accueil')}}" {% if request.url_rule.endpoint=="professeur_routes.accueil"
        %}class="nav-link active" aria-current="page" {% else %}class="nav-link text-white" {% endif %}>
        <i class="fas fa-home"></i>
        <span class="ms-2">accueil</span>
      </a>
    </li>
  </ul>
  <hr>
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1"
      data-bs-toggle="dropdown" aria-expanded="false">
      <strong>{{session['email']}}</strong>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
      <li>
        <a class="dropdown-item" href="{{url_for('professeur_routes.deconnexion')}}">Se déconnecter</a>
      </li>
    </ul>
  </div>
</div>
{% block sub_content %}
{% endblock %}
{% endblock %}


{% block script %}
{% block sub_script %}
{% endblock %}
{% endblock %}