stack/website/secondtour_website/website/routes/main_routes.py
import logging
import traceback
from flask import Blueprint, render_template, session, request, redirect, url_for
from flask.helpers import flash
import requests
import os

from ..database.main_database import *
from ..function import main_security, main_sessions

main_routes = Blueprint('main_routes', __name__,
                        template_folder='templates',
                        static_folder='static')

@main_routes.route('/')
@main_routes.route('/index')
def index():
    
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-home",
            "data": {
                "target": "website:website-home"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-home:website-home-home",
            "data": {
                "target": "website-home:website-home-home"
            }
        })
    
    # ask for data
    response = ask_api("data/fetchmulti", ["candidat", "creneau", "serie", "matiere", "salle"])
    if response.status_code != 200:
        flash("Une erreur est survenue lors de la récupération des données", "danger")
    all_candidats, all_creneaux, all_series, all_matieres, all_salles = response.json()
    
    all_creneaux.sort(key=lambda creneau: creneau['debut_preparation'])
    for creneau in all_creneaux:
                creneau["debut_preparation"] = datetime.strptime(creneau["debut_preparation"], '%a %b %d %H:%M:%S %Y') if type(creneau["debut_preparation"]) == str else creneau["debut_preparation"]
                creneau["fin_preparation"] = datetime.strptime(creneau["fin_preparation"], '%a %b %d %H:%M:%S %Y') if type(creneau["fin_preparation"]) == str else creneau["fin_preparation"]
                creneau["fin"] = datetime.strptime(creneau["fin"], '%a %b %d %H:%M:%S %Y') if type(creneau["fin"]) == str else creneau["fin"]

    return render_template('index.html', all_candidats=all_candidats, all_creneaux=all_creneaux, all_series=all_series, all_matieres=all_matieres, all_salles=all_salles)

@main_routes.route('/connexion', methods=['POST', 'GET'])
def connexion():
    
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-home",
            "data": {
                "target": "website:website-home"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-home:website-home-connexion",
            "data": {
                "target": "website-home:website-home-connexion"
            }
        })
    
    if request.method == 'GET':
            if main_security.test_session_connected(session, True):
                return redirect(url_for('admin_routes.accueil'))
            elif main_security.test_session_connected(session, False):
                return redirect(url_for('professeur_routes.accueil'))
            else:
                return render_template('connexion.html')
    else:
        form = request.form
        if 'email' not in form or 'password' not in form:
            flash('Une erreur est survenue', 'danger')
            logging.warning('Une erreur est survenue, il m\anquai l\'email ou le mot de passe')
            return render_template('connexion.html')
        email, password = form['email'], form['password']
        # Verify that there valid
        try:
            response = ask_api("data/fetchfilter/utilisateur", {"email": email, "admin": "true"})
            if response.status_code != 200:
                flash("Une erreur est survenue lors de la récupération des données", "danger")
                logging.warning("Une erreur est survenue lors de la recuperation des donnees utilisateur")
            user = response.json()[0] if response.json() else None
            # user = UTILISATEUR.query.filter_by(email=email, admin=True).first()
            if not user:
                response = ask_api("data/fetchfilter/utilisateur", {"email": email, "admin": "false"})
                if response.status_code != 200:
                    flash("Une erreur est survenue lors de la récupération des données", "danger")
                    logging.warning("Une erreur est survenue lors de la recuperation des donnees utilisateur")
                user = response.json()[0] if response.json() else None
                # user = UTILISATEUR.query.filter_by(email=email, admin=False).first()
            # Verify that the user exist
            if user:
                # Verify the password
                if main_security.test_password(password, user):
                    # User exist
                    # Save in session
                    main_sessions.save_user(session, user)
                    # Go to dashboard
                    logging.warning('Connexion reussie')
                    return redirect(url_for('admin_routes.accueil'))
                else:
                    flash('Cet utilisateur n\'existe pas', 'warning')
                    logging.warning('Cet utilisateur n\'existe pas (incorrect password)')
                    return render_template('connexion.html'), 401
            else:
                flash('Cet utilisateur n\'existe pas', 'warning')
                logging.warning('Cet utilisateur n\'existe pas')
                return render_template('connexion.html'), 401
            
        except Exception:
            flash('Cet utilisateur n\'existe pas', 'warning')
            logging.warning(traceback.format_exc().encode("utf-8"))
            logging.warning('Cet utilisateur n\'existe pas + erreur code')
    return render_template('connexion.html')

@main_routes.route('/cgu')
def cgu():
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-home",
            "data": {
                "target": "website:website-home"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-home:website-home-cgu",
            "data": {
                "target": "website-home:website-home-cgu"
            }
        })
    
    return render_template('cgu.html')


if(os.getenv("NETWORK_VISU") == "true"):
    
    
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home",
        "data": {
                "name": "Accueil",
                "id": "website-home",
                "size": 46,
                "fsize": 30
        },
        "position": {
            "x": 353,
            "y": 707
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website:website-home",
        "data": {
                "id": "website:website-home",
                "weight": 1,
                "source": "website",
                "target": "website-home"
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home-home",
        "data": {
                "name": "Pade d'accueil",
                "id": "website-home-home",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 272,
            "y": 745
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-home:website-home-home",
        "data": {
                "id": "website-home:website-home-home",
                "weight": 1,
                "source": "website-home",
                "target": "website-home-home"
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home-cgu",
        "data": {
                "name": "CGU",
                "id": "website-home-cgu",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 315,
            "y": 782
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-home:website-home-cgu",
        "data": {
                "id": "website-home:website-home-cgu",
                "weight": 1,
                "source": "website-home",
                "target": "website-home-cgu"
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home-connexion",
        "data": {
                "name": "Connexion",
                "id": "website-home-connexion",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 372,
            "y": 793
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-home:website-home-connexion",
        "data": {
                "id": "website-home:website-home-connexion",
                "weight": 1,
                "source": "website-home",
                "target": "website-home-connexion"
        }
    })

stack/website/secondtour_website/website/routes/register_routes.py
import logging
import traceback
from flask import Blueprint, render_template, session, request, redirect, url_for, send_file
from flask.helpers import flash
import os


from ..function import main_security, main_sessions, main_database, main_calendrier
from ..database.main_database import *
from ..main_website import app

register_routes = Blueprint('register_routes', __name__,
                            template_folder='templates',
                            static_folder='static')


@register_routes.route('/', methods=['POST', 'GET'])
def register():
    
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-professeur",
            "data": {
                "target": "website:website-professeur"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-professeur:website-professeur-compte",
            "data": {
                "target": "website-professeur:website-professeur-compte"
            }
        })
    
    if request.method == "POST":
        form = request.form
        if 'email' in form and 'token' in form and 'password' in form:
            try:
                response = ask_api("data/fetchfilter/token", {"token": form['token']})
                if response.status_code != 200:
                    flash("Une erreur est survenue lors de la récupération des données", "danger")
                exist = response.json()[0] if response else None
                # exist = TOKEN.query.filter_by(token=form['token']).one()
                if exist and exist['email'] == form['email']:
                    user = main_database.add_account(form['email'], form['password'], 'Professeur', output=True)
                    if user[1][1] == 'danger':
                        flash(user[1][0], user[1][1])
                    else:
                        logging.warning(f"Le compte du professeur {form['email']} à bien été crée")
                        main_database.delete_token(form['token'])
                        logging.warning(f"Le token à en conséquent été supprimé")
                        return redirect(url_for('main_routes.connexion'))
                else:
                    flash("L'adresse saisie est incorrecte", "danger")
            except Exception:
                traceback.print_exc()
                flash("L'adresse saisie est incorrecte", "danger")
        return render_template('register/register.html', token=form["token"], email=form["email"])
    else:
        token = request.args.get('token')
        try:
            response = ask_api("data/fetchfilter/token", {"token": token})
            if response.status_code != 200:
                flash("Une erreur est survenue lors de la récupération des données", "danger")
            if response:
                email = response.json()[0]['email'] if response.json() else None
            else:
                email = None
            # email = TOKEN.query.filter_by(token=token).one().email
            return render_template('register/register.html', token=token, email=email)
        except Exception:
            traceback.print_exc()
            logging.warning("Invalid token")
            return render_template('register/register.html', token="error", email="error")

stack/website/secondtour_website/website/templates/register/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>S'enregistrer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" />

    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='img/logo_square.ico')}}" />

</head>

<body>
    <main id="main" style="height: 100%;">
        <div class="d-flex justify-content-center align-items-center mt-5 mb-4" style="height: 30%;">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo" style="height: 30%; width:auto;">
        </div>
        <div class="m-5">
            {%- for category, message in get_flashed_messages(with_categories = true) %}
            <div class="alert alert-{{category}}  alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {%- endfor %}
        </div>
        <div>
            <form method="post" action="{{url_for('register_routes.register')}}" style="width: 100%;"
                class="d-flex flex-column align-items-center" id="myform">
                <input type="text" hidden value="{{ token }}" name="token">
                <div class="form-login-input-lg margin-login-form">
                    <input type="email" class="form-control" readonly id="floatingInput" value="{{ email }}"
                        name="email" required>
                </div>
                <div class="form-floating form-login-input-lg margin-login-form d-flex">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="MotDePasse"
                        name="password" required>
                    <i class="bi bi-eye-slash d-flex justify-content-center align-items-center eye-form"
                        id="togglePassword"></i>
                    <label for="floatingPassword">Mot de passe</label>
                </div>
                <div class="form-floating form-login-input-lg margin-login-form d-flex needs-validation">
                    <input type="password" class="form-control" id="floatingPasswordConfirmation"
                        placeholder="MotDePasse" name="password_confirm" required>
                    <label for="floatingPassword">Confirmer le mot de passe</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault" style="color:white">
                        En cochant cette case vous confirmez avoir lu et accepté les <a
                            href="{{url_for('main_routes.cgu')}}" style="color:blue">conditions générales
                            d'utilisation.</a>
                    </label>
                </div>
                <div class="form-login-input-lg">
                    <button class="w-100 btn btn-lg btn-primary margin-login-form btn-success" type="button"
                        onclick="submit_form()">S'inscrire</button>
                </div>
            </form>
        </div>
    </main>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

<script>

    const togglePassword = document.querySelector('#togglePassword');
    const password = document.querySelector('#floatingPassword');

    if (togglePassword && password) {
        togglePassword.addEventListener('click', function (e) {
            // toggle the type attribute
            const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
            password.setAttribute('type', type);
            // toggle the eye / eye slash icon
            this.classList.toggle('bi-eye');
        });
    }


    function submit_form() {
        let password1 = document.querySelector('#floatingPassword');
        //let password1 document.getElementById('#Password1');//.elements
        let password_confirm = document.querySelector('#floatingPasswordConfirmation');
        let CGUcheck = document.querySelector('#flexCheckDefault').checked;
        if (password1.value != password_confirm.value) {
            alert("Les deux mots de passe ne correspondent pas")
        }
        else if (CGUcheck == false) {
            alert("Vous devez accepter les conditions générales d'utilisation")
        }
        else {
            document.forms['myform'].submit();
        }
    }



</script>

</html>