stack/website/secondtour_website/website/routes/main_routes.py
import logging
import traceback
from flask import Blueprint, render_template, session, request, redirect, url_for
from flask.helpers import flash
import requests
import os

from ..database.main_database import *
from ..function import main_security, main_sessions

main_routes = Blueprint('main_routes', __name__,
                        template_folder='templates',
                        static_folder='static')

@main_routes.route('/')
@main_routes.route('/index')
def index():
    
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-home",
            "data": {
                "target": "website:website-home"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-home:website-home-home",
            "data": {
                "target": "website-home:website-home-home"
            }
        })
    
    # ask for data
    response = ask_api("data/fetchmulti", ["candidat", "creneau", "serie", "matiere", "salle"])
    if response.status_code != 200:
        flash("Une erreur est survenue lors de la récupération des données", "danger")
    all_candidats, all_creneaux, all_series, all_matieres, all_salles = response.json()
    
    all_creneaux.sort(key=lambda creneau: creneau['debut_preparation'])
    for creneau in all_creneaux:
                creneau["debut_preparation"] = datetime.strptime(creneau["debut_preparation"], '%a %b %d %H:%M:%S %Y') if type(creneau["debut_preparation"]) == str else creneau["debut_preparation"]
                creneau["fin_preparation"] = datetime.strptime(creneau["fin_preparation"], '%a %b %d %H:%M:%S %Y') if type(creneau["fin_preparation"]) == str else creneau["fin_preparation"]
                creneau["fin"] = datetime.strptime(creneau["fin"], '%a %b %d %H:%M:%S %Y') if type(creneau["fin"]) == str else creneau["fin"]

    return render_template('index.html', all_candidats=all_candidats, all_creneaux=all_creneaux, all_series=all_series, all_matieres=all_matieres, all_salles=all_salles)

@main_routes.route('/connexion', methods=['POST', 'GET'])
def connexion():
    
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-home",
            "data": {
                "target": "website:website-home"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-home:website-home-connexion",
            "data": {
                "target": "website-home:website-home-connexion"
            }
        })
    
    if request.method == 'GET':
            if main_security.test_session_connected(session, True):
                return redirect(url_for('admin_routes.accueil'))
            elif main_security.test_session_connected(session, False):
                return redirect(url_for('professeur_routes.accueil'))
            else:
                return render_template('connexion.html')
    else:
        form = request.form
        if 'email' not in form or 'password' not in form:
            flash('Une erreur est survenue', 'danger')
            logging.warning('Une erreur est survenue, il m\anquai l\'email ou le mot de passe')
            return render_template('connexion.html')
        email, password = form['email'], form['password']
        # Verify that there valid
        try:
            response = ask_api("data/fetchfilter/utilisateur", {"email": email, "admin": "true"})
            if response.status_code != 200:
                flash("Une erreur est survenue lors de la récupération des données", "danger")
                logging.warning("Une erreur est survenue lors de la recuperation des donnees utilisateur")
            user = response.json()[0] if response.json() else None
            # user = UTILISATEUR.query.filter_by(email=email, admin=True).first()
            if not user:
                response = ask_api("data/fetchfilter/utilisateur", {"email": email, "admin": "false"})
                if response.status_code != 200:
                    flash("Une erreur est survenue lors de la récupération des données", "danger")
                    logging.warning("Une erreur est survenue lors de la recuperation des donnees utilisateur")
                user = response.json()[0] if response.json() else None
                # user = UTILISATEUR.query.filter_by(email=email, admin=False).first()
            # Verify that the user exist
            if user:
                # Verify the password
                if main_security.test_password(password, user):
                    # User exist
                    # Save in session
                    main_sessions.save_user(session, user)
                    # Go to dashboard
                    logging.warning('Connexion reussie')
                    return redirect(url_for('admin_routes.accueil'))
                else:
                    flash('Cet utilisateur n\'existe pas', 'warning')
                    logging.warning('Cet utilisateur n\'existe pas (incorrect password)')
                    return render_template('connexion.html'), 401
            else:
                flash('Cet utilisateur n\'existe pas', 'warning')
                logging.warning('Cet utilisateur n\'existe pas')
                return render_template('connexion.html'), 401
            
        except Exception:
            flash('Cet utilisateur n\'existe pas', 'warning')
            logging.warning(traceback.format_exc().encode("utf-8"))
            logging.warning('Cet utilisateur n\'existe pas + erreur code')
    return render_template('connexion.html')

@main_routes.route('/cgu')
def cgu():
    if(os.getenv("NETWORK_VISU") == "true"):
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website:website-home",
            "data": {
                "target": "website:website-home"
            }
        })
        requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
            "type": "trigger",
            "name": "website-home:website-home-cgu",
            "data": {
                "target": "website-home:website-home-cgu"
            }
        })
    
    return render_template('cgu.html')


if(os.getenv("NETWORK_VISU") == "true"):
    
    
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home",
        "data": {
                "name": "Accueil",
                "id": "website-home",
                "size": 46,
                "fsize": 30
        },
        "position": {
            "x": 353,
            "y": 707
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website:website-home",
        "data": {
                "id": "website:website-home",
                "weight": 1,
                "source": "website",
                "target": "website-home"
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home-home",
        "data": {
                "name": "Pade d'accueil",
                "id": "website-home-home",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 272,
            "y": 745
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-home:website-home-home",
        "data": {
                "id": "website-home:website-home-home",
                "weight": 1,
                "source": "website-home",
                "target": "website-home-home"
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home-cgu",
        "data": {
                "name": "CGU",
                "id": "website-home-cgu",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 315,
            "y": 782
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-home:website-home-cgu",
        "data": {
                "id": "website-home:website-home-cgu",
                "weight": 1,
                "source": "website-home",
                "target": "website-home-cgu"
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "node",
        "name": "website-home-connexion",
        "data": {
                "name": "Connexion",
                "id": "website-home-connexion",
                "size": 28,
                "fsize": 20
        },
        "position": {
            "x": 372,
            "y": 793
        }
    })
    requests.post("http://"+os.getenv("LOCAL_IP")+":3000/add", json={
        "type": "edge",
        "name": "website-home:website-home-connexion",
        "data": {
                "id": "website-home:website-home-connexion",
                "weight": 1,
                "source": "website-home",
                "target": "website-home-connexion"
        }
    })

stack/website/secondtour_website/website/templates/cgu.html
{% extends "base.html" %}
{% block title %} Conditions Générales d'Utilisation {% endblock %}
{% block content %}
<div class="d-flex flex-column align-items-center min-width-max-content pt-m maxh">
  <div class="mb-m">
    <a href="{{url_for('main_routes.index')}}">
      <img alt="logo" src="{{url_for('static', filename='img/logo.png')}}" class="image-m"></a>
  </div>
  <embed src={{url_for('static', filename='pdf-docx/cgu.pdf')}} width=1200 height=800 type='application/pdf' frameBorder="0"  scrolling="auto"/>
</div>

{% endblock %}

{% block script %}
{% endblock %}

{% block footer %}
<!-- Grid container -->
<div class="container p-1" style="font-size: small; ; ">
    <!--Grid row-->
    <div class="row" style="display: flex; justify-content: center" >
      <!--Grid column-->
      
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <P class="text-uppercase mb-0">Adresse :</p>

          <ul class="list-unstyled mb-0 text-white">
            <li>
              <p>118 rue des Gonthières, 17 026 La Rochelle CEDEX 01</p>
            </li>
         </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <p class="text-uppercase mb-0"></p>

        <ul class="list-unstyled ">
          <li>
           <p>Telephone : <a class="text-white" href="tel:0546347932">05 46 34 79 32</a></p>
          </li>
          <li>
            <a class="text-white" href="{{url_for('main_routes.cgu')}}">conditions générales d'utilisation</a>
          </li>
          <li>
            <p>Fax : 05 46 34 22 28</p>
          </li>
         </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <p class="text-uppercase mb-0">Adresse mail :</p>

        <ul class="list-unstyled">
          <li>
            <a class="text-white" href="mailto:contact@lycee-vieljeux.fr">contact@lycee-vieljeux.fr</a>
          </li>
         </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2); font-size: medium;display: flex; justify-content: center; ">
    <p>© 2021 Copyright : IUT de La Rochelle</p>
  </div>
  <!-- Copyright -->
{% endblock %}

stack/website/secondtour_website/website/templates/connexion.html
{% extends "base.html" %}
{% block title %} Se connecter {% endblock %}
{% block content %}
<div class="d-flex flex-column align-items-center min-width-max-content pt-m maxh">
  <div class="mb-m">
    <a href="{{url_for('main_routes.index')}}">
      <img alt="logo" src="{{url_for('static', filename='img/logo.png')}}" class="image-m"></a>
  </div>
  <div class="d-flex flex-column align-items-center justify-content-center mt-xxl" style="width:80%;">
    <form method="post" action="{{url_for('main_routes.connexion')}}" style="width: 100%;" class="d-flex flex-column align-items-center">
      <div class="form-floating form-login-input-lg margin-login-form">
        <input type="email" class="form-control" id="floatingInput" placeholder="name@exemple.com" name="email"
          required="required">
        <label for="floatingInput">Adresse email</label>
      </div>
      <div class="form-floating form-login-input-lg margin-login-form d-flex">
        <input type="password" class="form-control" id="floatingPassword" placeholder="MotDePasse" name="password"
          required="required">
        <i class="bi bi-eye-slash d-flex justify-content-center align-items-center eye-form" id="togglePassword"></i>
        <label for="floatingPassword">Mot de passe</label>
      </div>
      <div class="form-login-input-lg">
        <button class="w-100 btn btn-lg btn-primary margin-login-form btn-success" type="submit">Se connecter</button>
      </div>
    </form>
    {%- for category, message in get_flashed_messages(with_categories = true) %}
    <div class="alert alert-{{category}}  alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%- endfor %}
  </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

{% block footer %}
<!-- Grid container -->
<div class="container p-1" style="font-size: small; ; ">
    <!--Grid row-->
    <div class="row" style="display: flex; justify-content: center" >
      <!--Grid column-->
      
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <P class="text-uppercase mb-0">Adresse :</p>

          <ul class="list-unstyled mb-0 text-white">
            <li>
              <p>118 rue des Gonthières, 17 026 La Rochelle CEDEX 01</p>
            </li>
         </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <p class="text-uppercase mb-0"></p>

        <ul class="list-unstyled ">
          <li>
           <p>Telephone : <a class="text-white" href="tel:0546347932">05 46 34 79 32</a></p>
          </li>
          <li>
            <p>Fax : 05 46 34 22 28</p>
          </li>
         </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <p class="text-uppercase mb-0">Adresse mail :</p>

        <ul class="list-unstyled">
          <li>
            <a class="text-white" href="mailto:contact@lycee-vieljeux.fr">contact@lycee-vieljeux.fr</a>
          </li>
         </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-1" style="background-color: rgba(0, 0, 0, 0.2); font-size: medium;display: flex; justify-content: center; ">
    <p>© 2021 Copyright : IUT de La Rochelle</p>
  </div>
  <!-- Copyright -->
{% endblock %}

stack/website/secondtour_website/website/templates/index.html
{% extends "base.html" %}
{% block title %}Calendrier{% endblock %}
{% block content %}
<div class="top-layer">
    <a href="{{url_for('main_routes.connexion')}}">
        <img alt="logo de connexion" src="{{url_for('static', filename='img/user.png')}}" class="image-login">
    </a>
</div>
<div class="d-flex flex-column align-items-center min-width-max-content">
    <div class="mb-l">
        <img alt="logo" src="{{url_for('static', filename='img/logo.png')}}" class="image-m">
    </div>
    {%- for category, message in get_flashed_messages(with_categories = true) %}
    <div class="alert alert-{{category}}  alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%- endfor %}
    <div class="padding-main-calendar">
        <div class="calendar table-responsive">
            <div class="name-finder" style="width: max-content;">
                <input class="form-control" type="text" id="search-name" v-on:keyup="nameFinder()"
                    placeholder="Recherche par nom..">
                <select class="form-select finder" v-on:change="multipleFinder([4, 6], 0)">
                    <option selected></option>
                    <option value="01">Jour 1</option>
                    <option value="02">Jour 2</option>
                    <option value="03">Jour 3</option>
                </select>
            </div>
            <div class="thumbnail" style="overflow: hidden;">
                <table class="table table-light table-striped calendar">
                    <thead>
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Prénom</th>
                            <th scope="col">Série</th>
                            <th scope="col">Epreuve 1</th>
                            <th scope="col">Epreuve 2</th>
                            <th scope="col" hidden>JourE1</th>
                            <th scope="col" hidden>JourE2</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for serie in all_series %}
                        {% for candidat in all_candidats %}
                        {% if candidat.id_serie == serie.id_serie and serie.nom == "Générale" %}
                        <tr>
                            <td scope="row">{{candidat.nom}}</td>
                            <td scope="row">{{candidat.prenom}}</td>
                            {% for serie in all_series %}
                            {% if serie.id_serie == candidat.id_serie %}
                            <td scope="row">
                                {{serie.nom}} - {% if serie.specialite1 %}{{serie.specialite1}}{% endif %}{% if
                                serie.specialite2 %}/{{serie.specialite2}}{% endif %}
                            </td>
                            {% endif %}
                            {% endfor %}
                            {% for creneau in all_creneaux %}
                            {% if creneau.id_candidat == candidat.id_candidat %}
                            <td scope="row">
                                <div class="calendar-subject">
                                    {% for matiere in all_matieres %}
                                    {% if matiere.id_matiere == creneau.id_matiere %}
                                    <div>{{matiere.nom}} - {% if matiere.loge %}Loge {% for salle in all_salles %}{% if
                                        matiere.loge == salle.id_salle %}{{salle.numero}}{% endif %}{% endfor %}{% else
                                        %}
                                        {% for salle in all_salles %}
                                        {% if salle.id_salle == creneau.id_salle %}
                                        {{salle.numero}}
                                        {% endif %}
                                        {% endfor %}
                                        {% endif %}</div>
                                    <div>{{creneau.debut_preparation.strftime('%d')}} |
                                        {{creneau.debut_preparation.strftime('%Hh%M')}} - {{creneau.fin.strftime('%Hh%M')}}</div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </td>
                            <td hidden>
                                {{creneau.debut_preparation.strftime('%d')}}
                            </td>
                            {% endif %}
                            {% endfor %}
                        </tr>
                        {% endif %}
                        {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <br>
            <div class="thumbnail" style="overflow: hidden;">
                <table class="table table-light table-striped calendar">
                    <thead>
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Prénom</th>
                            <th scope="col">Série</th>
                            <th scope="col">Epreuve 1</th>
                            <th scope="col">Epreuve 2</th>
                            <th scope="col" hidden>JourE1</th>
                            <th scope="col" hidden>JourE2</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for serie in all_series %}
                        {% for candidat in all_candidats %}
                        {% if candidat.id_serie == serie.id_serie and serie.nom == "Technologique" %}
                        <tr>
                            <td scope="row">{{candidat.nom}}</td>
                            <td scope="row">{{candidat.prenom}}</td>
                            {% for serie in all_series %}
                            {% if serie.id_serie == candidat.id_serie %}
                            <td scope="row">
                                {{serie.nom}} - {% if serie.specialite1 %}{{serie.specialite1}}{% endif %}{% if
                                serie.specialite2 %}/{{serie.specialite2}}{% endif %}
                            </td>
                            {% endif %}
                            {% endfor %}
                            {% for creneau in all_creneaux %}
                            {% if creneau.id_candidat == candidat.id_candidat %}
                            <td scope="row">
                                <div class="calendar-subject">
                                    {% for matiere in all_matieres %}
                                    {% if matiere.id_matiere == creneau.id_matiere %}
                                    <div>{{matiere.nom}} - {% if matiere.loge %}Loge {% for salle in all_salles %}{% if
                                        matiere.loge == salle.id_salle %}{{salle.numero}}{% endif %}{% endfor %}{% else
                                        %}
                                        {% for salle in all_salles %}
                                        {% if salle.id_salle == creneau.id_salle %}
                                        {{salle.numero}}
                                        {% endif %}
                                        {% endfor %}
                                        {% endif %}</div>
                                    <div>{{creneau.debut_preparation.strftime('%d')}} |
                                        {{creneau.debut_preparation.strftime('%Hh%M')}} - {{creneau.fin.strftime('%Hh%M')}}</div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </td>
                            <td hidden>
                                {{creneau.debut_preparation.strftime('%d')}}
                            </td>
                            {% endif %}
                            {% endfor %}
                        </tr>
                        {% endif %}
                        {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Background
<canvas class="background"></canvas> -->
{% endblock %}

{% block script %}
{% endblock %}

{% block footer %}
<!-- Grid container -->
<div class="container p-1" style="font-size: small; ; ">
    <!--Grid row-->
    <div class="row" style="display: flex; justify-content: center">
        <!--Grid column-->

        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <P class="text-uppercase mb-0">Adresse :</p>

            <ul class="list-unstyled mb-0 text-white">
                <li>
                    <p>118 rue des Gonthières, 17 026 La Rochelle CEDEX 01</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <p class="text-uppercase mb-0"></p>

            <ul class="list-unstyled ">
                <li>
                    <p>Telephone : <a class="text-white" href="tel:0546347932">05 46 34 79 32</a></p>
                </li>
                <li>
                    <a class="text-white" href="{{url_for('main_routes.cgu')}}">conditions générales d'utilisation</a>
                </li>
                <li>
                    <p>Fax : 05 46 34 22 28</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <p class="text-uppercase mb-0">Adresse mail :</p>

            <ul class="list-unstyled">
                <li>
                    <a class="text-white" href="mailto:contact@lycee-vieljeux.fr">contact@lycee-vieljeux.fr</a>
                </li>
            </ul>
        </div>
        <!--Grid column-->
    </div>
    <!--Grid row-->
</div>
<!-- Grid container -->

<!-- Copyright -->
<div class="text-center p-1"
    style="background-color: rgba(0, 0, 0, 0.2); font-size: medium;display: flex; justify-content: center; ">
    <p>© 2021 Copyright : IUT de La Rochelle</p>
</div>
<!-- Copyright -->
{% endblock %}